# -*- coding: utf-8 -*-
"""solar_power_gen_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWp5GhiE1624GWGrCQEjnU4hu-rIOMPp
"""

import streamlit as st
import joblib
import pandas as pd

# ==============================
# Load Trained Model
# ==============================
model = joblib.load("Solar_power_gen037.pkl")

st.title("☀️ Solar Power Generation Prediction")

st.write("Enter weather details to predict solar power generation.")

# ==============================
# User Inputs
# ==============================

average_temperature = st.number_input("Average Temperature (Day)", format="%.2f")
average_wind_speed = st.number_input("Average Wind Speed (Day)", format="%.2f")
sky_cover = st.number_input("Sky Cover")
relative_humidity = st.number_input("Relative Humidity", format="%.2f")
visibility = st.number_input("Visibility", format="%.2f")
distance_to_solar_noon = st.number_input("Distance to Solar Noon", format="%.2f")
average_barometric_pressure = st.number_input("Average Barometric Pressure (Period)", format="%.2f")
is_daylight = st.selectbox("Is Daylight?", [0, 1])

# ==============================
# Create Input DataFrame
# ==============================

input_data = pd.DataFrame([[
    average_temperature,
    average_wind_speed,
    sky_cover,
    relative_humidity,
    visibility,
    distance_to_solar_noon,
    average_barometric_pressure,
    is_daylight
]], columns=model.feature_names_in_)

# ==============================
# Prediction
# ==============================

if st.button("Predict"):
    prediction = model.predict(input_data)[0]

    st.success(f"⚡ Predicted Solar Power Generation: {prediction:.2f}")
