# -*- coding: utf-8 -*-
"""Solar_App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKm7pG9gz5rlUHUHkIPsqFFsiGFN5run
"""

import streamlit as st
import pandas as pd
import joblib

# Load model and encoder
model = joblib.load("solar_model.pkl")
encoder = joblib.load("label_encoder.pkl")

st.title("Solar Power Prediction")

# Inputs
temperature = st.number_input("Average Temperature (Day)", -10.0, 50.0)
wind_speed = st.number_input("Average Wind Speed (Day)", 0.0, 50.0)
sky_cover = st.number_input("Sky Cover", 0, 10)
distance_noon = st.number_input("Distance to Solar Noon", 0.0, 1.0)
is_daylight = st.selectbox("Is Daylight", encoder["Is Daylight"].classes_)

df = pd.DataFrame({
    "Average Temperature (Day)": [temperature],
    "Average Wind Speed (Day)": [wind_speed],
    "Sky Cover": [sky_cover],
    "Distance to Solar Noon": [distance_noon],
    "Is Daylight": [is_daylight]
})

if st.button("Predict"):

    for col in encoder.keys():
        if col in df.columns:
            df[col] = encoder[col].transform(df[col])

    prediction = model.predict(df)

    st.write("Predicted Power Generated:", round(prediction[0], 2))